### PR TITLE
fix(Velocity): return correct velocities

### PR DESCRIPTION
**Pull request by fight4dream**
ConstantVelocityTracker is intended to be like the physics Constant Force component. If UseLocal=false, it should return velocity in absolute world space frame. If UseLocal=true, it should return velocity in attached object reference frame.

### CODE REVIEW

**Comment by fight4dream** [comment]
#581

**Comment by thestonefox** [comment]
is it worth writing a unit test to prove this is working as expected?

**Comment by fight4dream** [comment]
there is a unit test for ConstantVelocityTracker. but because the test subject is a top level object, its localRotation is the same as rotation. thus the new change still passed the old test 🫣

it will need a multi level hierarchy and slightly weird angles to make sure it is working as expected

**Comment by thestonefox** [comment]
do you want this just merged then without adding the additional tests?

**Comment by thestonefox** [comment]
These are the updated tests if you want to add them:

```
        [Test]
        public void GetVelocityUseLocal()
        {
            Vector3EqualityComparer comparer = new Vector3EqualityComparer(0.1f);
            GameObject parent = new GameObject("ConstantVelocityTrackerTest_Parent");
            containingObject.transform.SetParent(parent.transform);

            Vector3 givenVelocity = new Vector3(-1.4f, 1.3f, 1.2f);
            Vector3 expectedResult = new Vector3(1.2f, 1.3f, 1.4f);
            Vector3 unexpectedResult = Vector3.zero;

            subject.UseLocal = true;
            subject.Velocity = givenVelocity;
            parent.transform.Rotate(0, 90, 0, Space.Self);

            Vector3 actualResult = subject.GetVelocity();
            Assert.That(actualResult, Is.EqualTo(expectedResult).Using(comparer));
            Assert.That(actualResult, Is.Not.EqualTo(unexpectedResult).Using(comparer));

            Object.DestroyImmediate(parent);
        }

        [Test]
        public void GetAngularVelocityUseLocal()
        {
            Vector3EqualityComparer comparer = new Vector3EqualityComparer(0.1f);
            GameObject parent = new GameObject("ConstantVelocityTrackerTest_Parent");
            containingObject.transform.SetParent(parent.transform);

            Vector3 givenVelocity = new Vector3(-1.4f, 1.3f, 1.2f);
            Vector3 expectedResult = new Vector3(1.2f, 1.3f, 1.4f);
            Vector3 unexpectedResult = Vector3.zero;

            subject.UseLocal = true;
            subject.AngularVelocity = givenVelocity;
            parent.transform.Rotate(0, 90, 0, Space.Self);

            Vector3 actualResult = subject.GetAngularVelocity();
            Assert.That(actualResult, Is.EqualTo(expectedResult).Using(comparer));
            Assert.That(actualResult, Is.Not.EqualTo(unexpectedResult).Using(comparer));

            Object.DestroyImmediate(parent);
        }
```

**Comment by thestonefox** [comment]
It's also worth adding tests for inactive component/gameobject as they shouldn't affect velocities when the component is not enabled in the scene:

```
        [Test]
        public void GetVelocityInactiveGameObject()
        {
            Vector3EqualityComparer comparer = new Vector3EqualityComparer(0.1f);

            subject.Velocity = new Vector3(1.2f, 1.3f, 1.4f);
            subject.gameObject.SetActive(false);

            Vector3 actualResult = subject.GetVelocity();
            Assert.That(actualResult, Is.EqualTo(Vector3.zero).Using(comparer));
        }

        [Test]
        public void GetVelocityInactiveComponent()
        {
            Vector3EqualityComparer comparer = new Vector3EqualityComparer(0.1f);

            subject.Velocity = new Vector3(1.2f, 1.3f, 1.4f);
            subject.enabled = false;

            Vector3 actualResult = subject.GetVelocity();
            Assert.That(actualResult, Is.EqualTo(Vector3.zero).Using(comparer));
        }
```

They both should just naturally pass

**Comment by thestonefox** [comment]
superseded by https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/583

**Pull request closed without merging**
